### ISSUE TITLE
where's modified llgo frontend?

### ISSUE THREAD

**Issue by aayupov** [ucb-hls/csp-hls#20]
Jenny, 

Apparently, the llgo in your repo as well as instructions in your final report are pointing to the reference llgo repo. Isn't it wrong? You said that you modified it to handle channels differently etc. But when I build it, I am getting the reference version that doesn't work with llvm-cbe later on. I also compared .s file that I generate with the reference llgo with .s file in your repo examples, and they are different. Yours has some references of FIFO type while the reference one doesn't obviously. Did you just not publish your llgo version on github or am I getting it wrong?

Thanks,
Andrey

**Comment by hqjenny** [comment]
Hi Andrey, the modified llgo is under:

https://github.com/ucb-hls/llgo

Best,
Jenny
